prior: Gaussian
seed: 72
epochs: 40 #100 # 80 #0 #00 500 #100 #220 #0 #
batch_size: 128 #512 #1024  #1604 # 802 #512 #
batch_size_model_s: 128
batch_size_model_t: 1604 #1024 # 128  #512  #
emb_size: 200

method: &method cdr_gan_gnn_dsi
log_prefix: logs
pos_weight: 1.0 # weight for positive samples


lr_t: 0.005 #8
lr_d: 0.0001
lr_g: 0.0001
weight_decay: 0.00002
dropout: 0.5

m: 2
scheme: ZP # PM, ZR, ZP #note 暂时没有用这些
zr_coefficient: 0.25  # alpha in the eq.7: range in {0.5, 0.25, 0.1, 0.05, 0.01} # careful: substitude it with weight_decay
S_zr_percentage: 50 # rang in {10, 30, 50, 70,90 }
S_pm_percentage: 50 # rang in {10, 30, 50, 70,90 }
is_PP: True #False #
#noise_multiplier_: 1 #000 #1.07 #0.55 #
#noise_multiplier_: 126 #1.07 #0.55 #
noise_multiplier_: 20 #1.07 #0.55 #

reg_orthogonal: 1.0
reg_raw: 1.0
reg_cross_trans: 1.0
d_g_steps: 2 #7 # 77 #
d_steps: 1 # 3 3 #
s_epochs: 3 # 4
t_s_epochs: 10 # 1

t_percent: 1.0
s_percent: 1.0
p_percent: 0.3

processed_data_dir:  ../processed_data
#DataIn: amazon
#dataset: amazon_review_full
#source: movie
#target: book
#si_emb_size: 768


#DataIn: amazon
#dataset: amazon2_review_full
#source: movie
#target: book
#si_emb_size: 768

#DataIn: amazon
#dataset: amazon3_review_full
#source: movie
#target: book
#si_emb_size: 768

#
#DataIn: douban
#dataset: movie_book_profile_full
#source: movie
#target: book
#si_emb_size: 128
#
#DataIn: douban
#dataset: movie_music_profile_full
#source: movie
#target: music
#si_emb_size: 128

DataIn: douban
dataset: book_music_profile_full
source: book
target: music
si_emb_size: 2 # 128






lamb_uu: 0.05 #1000 #
num_of_candidate_negative: 6 #32 # 负采样个数
loss_t_method: bpr #sml #

#negative sampling
ns_gamma: 0.5 # 控制diff user margin 的优化权重
ns_lamda: 0.5 #控制item triplet loss 的权重

knn_size: 5 #16 #
latent_size: 256
#pp_G_s_model_path:
#pp_G_s_model_path:
uuid_tag: test_model_si
#uuid_tag: test_0000_happy
